<a href="https://colab.research.google.com/github/mariel/Sisteme-Inteligente/blob/Lab2%263/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from torch.utils.data import Dataset, DataLoader
from torch import nn, from_numpy, optim
import numpy as np

import pandas as pd
import torch
import torch.nn as nn

In [0]:
df = pd.read_csv("/content/diabetes.csv",header = None)

In [3]:
df.values

array([[-0.294118 ,  0.487437 ,  0.180328 , ..., -0.53117  , -0.0333333,
         0.       ],
       [-0.882353 , -0.145729 ,  0.0819672, ..., -0.766866 , -0.666667 ,
         1.       ],
       [-0.0588235,  0.839196 ,  0.0491803, ..., -0.492741 , -0.633333 ,
         0.       ],
       ...,
       [-0.411765 ,  0.21608  ,  0.180328 , ..., -0.857387 , -0.7      ,
         1.       ],
       [-0.882353 ,  0.266332 , -0.0163934, ..., -0.768574 , -0.133333 ,
         0.       ],
       [-0.882353 , -0.0653266,  0.147541 , ..., -0.797609 , -0.933333 ,
         1.       ]])

In [0]:
class DiabetesDataset(Dataset):
    def __init__(self):
        df=pd.read_csv("/content/diabetes.csv",header=None, dtype=np.float32)
        xy = torch.from_numpy(df.values)
        self.len = xy.shape[0]
        self.x_data = xy[:, 0:-1]
        self.y_data = xy[:, [-1]]

    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    def __len__(self):
        return self.len

In [0]:
dataset = DiabetesDataset()
train_loader = DataLoader(dataset=dataset,
                          batch_size=32,
                          shuffle = True,
                          num_workers=1)

In [21]:
dataset[0]

(tensor([-0.2941,  0.4874,  0.1803, -0.2929,  0.0000,  0.0015, -0.5312, -0.0333]),
 tensor([0.]))

In [0]:
class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.l1 = nn.Linear(8,6)
    self.l2 = nn.Linear(6,4)
    self.l3 = nn.Linear(4,1)

    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out1 = self.sigmoid(self.l1(x))
    out2 = self.sigmoid(self.l2(out1))
    y_pred = self.sigmoid(self.l3(out2))
    return y_pred

In [0]:
model = Model()

In [0]:
criterion = nn.BCELoss(reduction = 'sum')
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [29]:
for epoch in range(200):
  for i,data in enumerate(train_loader, 0):
    inputs,labels = data
    y_pred = model(inputs)
    loss = criterion(y_pred, labels)
    print(f'Epoch{epoch + 1} | Batch: {i + 1} | Loss: {loss.item():.4f}')

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch1 | Batch: 1 | Loss: 22.7534
Epoch1 | Batch: 2 | Loss: 21.3839
Epoch1 | Batch: 3 | Loss: 21.9847
Epoch1 | Batch: 4 | Loss: 19.6232
Epoch1 | Batch: 5 | Loss: 23.0363
Epoch1 | Batch: 6 | Loss: 21.6203
Epoch1 | Batch: 7 | Loss: 20.8457
Epoch1 | Batch: 8 | Loss: 19.1505
Epoch1 | Batch: 9 | Loss: 22.9057
Epoch1 | Batch: 10 | Loss: 20.9114
Epoch1 | Batch: 11 | Loss: 22.6306
Epoch1 | Batch: 12 | Loss: 21.9042
Epoch1 | Batch: 13 | Loss: 20.6729
Epoch1 | Batch: 14 | Loss: 19.0429
Epoch1 | Batch: 15 | Loss: 20.8588
Epoch1 | Batch: 16 | Loss: 23.6042
Epoch1 | Batch: 17 | Loss: 23.4151
Epoch1 | Batch: 18 | Loss: 21.9193
Epoch1 | Batch: 19 | Loss: 20.5819
Epoch1 | Batch: 20 | Loss: 17.9838
Epoch1 | Batch: 21 | Loss: 23.1386
Epoch1 | Batch: 22 | Loss: 20.1832
Epoch1 | Batch: 23 | Loss: 19.8408
Epoch1 | Batch: 24 | Loss: 14.8967
Epoch2 | Batch: 1 | Loss: 21.9112
Epoch2 | Batch: 2 | Loss: 19.8626
Epoch2 | Batch: 3 | Loss: 16.8256
Epoch2 | Batch: 4 | Loss: 23.0522
Epoch2 | Batch: 5 | Loss: 21.1389